source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'ZGHttp_Example' do
  pod 'ZGHttp', :path => '../'
  target 'ZGHttp_Tests' do
    inherit! :search_paths

    
  end
end
